### ISSUE TITLE
Capture variables from env for closure should be immutable 

### ISSUE THREAD

**Issue by killme2008** [killme2008/aviator#101]
For example

```java
  String exp = "a=1; b = lambda(x) -> a+ x end ; a=4 ; b(5)";
    System.out.println(AviatorEvaluator.execute(exp)); // output 6
```

should output `6`, but now is 9.

**Comment by killme2008** [comment]
Now it will throw an exception for such assigment:

```java
Exception in thread "main" com.googlecode.aviator.exception.ExpressionRuntimeException: Can't assignment value to captured variable.The `a` is already captured by lambda.
	at com.googlecode.aviator.utils.Env.put(Env.java:217)
	at com.googlecode.aviator.utils.Env.put(Env.java:1)
	at com.googlecode.aviator.runtime.type.AviatorJavaType.setValue(AviatorJavaType.java:264)
	at Script_1547125754122_0/1344622638.execute0(Unknown Source)
	at com.googlecode.aviator.ClassExpression.execute(ClassExpression.java:71)
	at com.googlecode.aviator.AviatorEvaluatorInstance.execute(AviatorEvaluatorInstance.java:741)
	at com.googlecode.aviator.AviatorEvaluator.execute(AviatorEvaluator.java:439)
	at com.googlecode.aviator.AviatorEvaluator.execute(AviatorEvaluator.java:451)
	at com.googlecode.aviator.AviatorEvaluator.execute(AviatorEvaluator.java:472)
	at com.googlecode.aviator.example.LambdaExample.main(LambdaExample.java:12)
```

**Comment by killme2008** [comment]
https://github.com/killme2008/aviator/releases/tag/aviator-4.1.2
