### ISSUE TITLE
when get a Number of null,then transform to AvitorDouble it throws NPE

### ISSUE THREAD

**Issue by jinjim** [killme2008/aviator#112]
when get a Number of null,then transform to AvitorDouble it throws NPE

**Comment by killme2008** [comment]
Please attach your code and explain the exception in detail, thanks.

**Comment by jinjim** [comment]
@Test
    public void test1() {
        
        String expression = "double(a)+double(b)-double(c)";

        Map<String, Object> env = new HashMap<>();
        env.put("a", 3.0);
        env.put("b", 4.0);
        Object result = AviatorEvaluator.execute("a+b+c", env);
        System.out.println(result);
    }

result:

com.googlecode.aviator.exception.ExpressionRuntimeException: Could not add Double(7.0) with JavaType(null, null)

	at com.googlecode.aviator.runtime.type.AviatorObject.add(AviatorObject.java:73)
	at com.googlecode.aviator.runtime.type.AviatorNumber.add(AviatorNumber.java:87)
	at Script_1551754202612_0/1750905143.execute0(Unknown Source)
	at com.googlecode.aviator.ClassExpression.execute(ClassExpression.java:53)
	at com.googlecode.aviator.AviatorEvaluator.execute(AviatorEvaluator.java:642)
	at com.googlecode.aviator.AviatorEvaluator.execute(AviatorEvaluator.java:657)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

**Comment by killme2008** [comment]
The exception is expected, you can add a number with null variable, c is null here, what's your problem?

**Comment by jinjim** [comment]
yes，c is null ,and actualy I Think it expected the result is 7.0

**Comment by killme2008** [comment]
sorry ,i don't think so it's not the rule of avator.

If you want the result ,please use ternary oeprator:

```
a+b+(c==nil? : 0: c)
```

**Comment by jinjim** [comment]
Yes,what you said is really what i am dealing with now,but it feels too cumbersome,so see if there are other more elegant ways.

**Comment by killme2008** [comment]
I think you can write a custom function such as 

```
AviatorEvaluator.define("n", "lambda(x) -> x == nil ? 0: x end");
```

Then call all the numbers with this function before using them:

```
n(a) + n(b) + n(c)
```

**Comment by killme2008** [comment]
Another solution is : you can get all the variables from expression by using `Expression#getVariableNames` method, then compare with your `env` map, if the var is not present, put it into env as zero.

**Comment by jinjim** [comment]
> Another solution is : you can get all the variables from expression by using `Expression#getVariableNames` method, then compare with your `env` map, if the var is not present, put it into env as zero.

Rewriting this can really solve this problem, but the impact is too big, let me try the first method.
