### ISSUE TITLE
高版本处理转义字符的问题

### ISSUE THREAD

**Issue by mo8396use** [killme2008/aviator#119]
aviator版本 4.1.1 处理如下转义字符时，
```
public class AviatorTest {
    @Test
    public void luohaoTest() {
        String str1 = "factor_dp_ugc_ssid == '\\\"WiredSSID\\\"'";
        Assert.assertNotNull(AviatorEvaluator.compile(str1, true));
    }
}
```
出现如下错误，异常堆栈信息如下，
```
com.googlecode.aviator.exception.CompileExpressionErrorException: Compile expression failure:factor_dp_ugc_ssid == '\"WiredSSID\"'
at com.googlecode.aviator.AviatorEvaluatorInstance.getCompiledExpression(AviatorEvaluatorInstance.java:642)
	at com.googlecode.aviator.AviatorEvaluatorInstance.compile(AviatorEvaluatorInstance.java:628)
	at com.googlecode.aviator.AviatorEvaluator.compile(AviatorEvaluator.java:400)
	at com.meituan.rc.zeus.AviatorTest.luohaoTest(AviatorTest.java:12)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.util.concurrent.ExecutionException: com.googlecode.aviator.exception.CompileExpressionErrorException: Unsupported escape character: \"
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:188)
	at com.googlecode.aviator.AviatorEvaluatorInstance.getCompiledExpression(AviatorEvaluatorInstance.java:639)
	... 9 more
Caused by: com.googlecode.aviator.exception.CompileExpressionErrorException: Unsupported escape character: \"
	at com.googlecode.aviator.lexer.ExpressionLexer.scan(ExpressionLexer.java:342)
	at com.googlecode.aviator.parser.ExpressionParser.move(ExpressionParser.java:772)
	at com.googlecode.aviator.parser.ExpressionParser.equality(ExpressionParser.java:277)
	at com.googlecode.aviator.parser.ExpressionParser.bitAnd(ExpressionParser.java:233)
	at com.googlecode.aviator.parser.ExpressionParser.xor(ExpressionParser.java:219)
	at com.googlecode.aviator.parser.ExpressionParser.bitOr(ExpressionParser.java:201)
	at com.googlecode.aviator.parser.ExpressionParser.and(ExpressionParser.java:251)
	at com.googlecode.aviator.parser.ExpressionParser.join(ExpressionParser.java:158)
	at com.googlecode.aviator.parser.ExpressionParser.ternary(ExpressionParser.java:137)
	at com.googlecode.aviator.parser.ExpressionParser.statement(ExpressionParser.java:797)
	at com.googlecode.aviator.parser.ExpressionParser.parse(ExpressionParser.java:787)
	at com.googlecode.aviator.AviatorEvaluatorInstance.innerCompile(AviatorEvaluatorInstance.java:651)
	at com.googlecode.aviator.AviatorEvaluatorInstance.access$000(AviatorEvaluatorInstance.java:98)
	at com.googlecode.aviator.AviatorEvaluatorInstance$2.call(AviatorEvaluatorInstance.java:619)
	at com.googlecode.aviator.AviatorEvaluatorInstance$2.call(AviatorEvaluatorInstance.java:616)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at com.googlecode.aviator.AviatorEvaluatorInstance.compile(AviatorEvaluatorInstance.java:626)
	... 8 more
```

但低版本3.0.0处理上述表达式时，不存在任何问题，编译正常通过，请问这种情况怎么解决，是因为高版本不兼容这种写法了吗？

**Comment by killme2008** [comment]
hello，其实这是因为低版本的转义处理是有 bug 的，在 4.x 版本做了系统修复，
你现在这个表达式可以简单写为，并不需要很多斜杠了

```
   String str1 = "factor_dp_ugc_ssid == '\"WiredSSID\"'";
    Expression e = (AviatorEvaluator.compile(str1, true));
    HashMap<String, Object> hashMap = new HashMap<>();
    hashMap.put("factor_dp_ugc_ssid", "\"WiredSSID\"");
    System.out.println(e.execute(hashMap));
```

具体 release note 参见

https://github.com/killme2008/aviator/releases/

**Comment by killme2008** [comment]
没有问题我关闭了。
