### ISSUE TITLE
BUG?无法拿到List的对象。

### ISSUE THREAD

**Issue by guangguangge** [killme2008/aviator#132]
BUG?无法拿到List的对象。    
BUG?无法拿到List的对象。
BUG?无法拿到List的对象。

		HashMap<String, Object> map=new HashMap<String,Object>();
		ArrayList<HashMap<String, Object>> list=new ArrayList<HashMap<String, Object>>();
		HashMap<String, Object> m=new HashMap<String,Object>();
		m.put("name", "wz");
		m.put("age", 11);
		list.add(m);
		map.put("aa", list);
		System.out.println(AviatorEvaluator.execute("aa[0].name", map));

		

	Exception in thread "main" com.googlecode.aviator.exception.ExpressionSyntaxErrorException: Syntax error:Unexpect token '.' at 5, current token: [type='Char',lexeme='.',index=5]. Parsing expression: `aa[0].^^`
	at com.googlecode.aviator.parser.ExpressionParser.reportSyntaxError(ExpressionParser.java:765)
	at com.googlecode.aviator.parser.ExpressionParser.parse(ExpressionParser.java:791)
	at com.googlecode.aviator.AviatorEvaluatorInstance.innerCompile(AviatorEvaluatorInstance.java:673)
	at com.googlecode.aviator.AviatorEvaluatorInstance.compile(AviatorEvaluatorInstance.java:653)
	at com.googlecode.aviator.AviatorEvaluatorInstance.execute(AviatorEvaluatorInstance.java:761)
	at com.googlecode.aviator.AviatorEvaluator.execute(AviatorEvaluator.java:439)
	at com.googlecode.aviator.AviatorEvaluator.execute(AviatorEvaluator.java:451)
	at Test_DB2.main(Test_DB2.java:30)

**Comment by killme2008** [comment]
使用 quote var

```
#aa[0].name
```

**Comment by guangguangge** [comment]
> 使用 quote var
> 
> ```
> #aa[0].name
> ```

也不对
    Exception in thread "main" com.googlecode.aviator.exception.ExpressionRuntimeException: Could not find variable aa[0].name

**Comment by killme2008** [comment]
sorry，是这样 `#aa.[0].name`

看这一节吧

https://github.com/killme2008/aviator/wiki#%E5%8F%98%E9%87%8F%E7%9A%84%E8%AF%AD%E6%B3%95%E7%B3%96

**Comment by guangguangge** [comment]
> sorry，是这样 `#aa.[0].name`
> 
> 看这一节吧
> 
> https://github.com/killme2008/aviator/wiki#%E5%8F%98%E9%87%8F%E7%9A%84%E8%AF%AD%E6%B3%95%E7%B3%96

额，试了多种方式。无论如何。name age都取不到
#aa[0]name
#aa.[0]name
#aa[0].name
#aa.[0].name

**Comment by killme2008** [comment]
你使用的版本可能太老了，升级下吧。我测试没有问题的。

**Comment by killme2008** [comment]
没有问题我先关闭了。
