### ISSUE TITLE
转义字符处理有BUG

### ISSUE THREAD

**Issue by FMX** [killme2008/aviator#150]
要执行的表达式如下：
`regex.find("\[",requestBody)` 

相关代码如下：
```  java 
		String exp = "regex.find(\"\\[\",requestBody) ";  
		AviatorEvaluator.addFunction(new AviatorRegularExpressionFunction());
        Expression expression = AviatorEvaluator.compile(exp);
        expression.execute();
```

得到的错误堆栈如下：

> com.googlecode.aviator.exception.CompileExpressionErrorException: Unsupported escape character: \[
	at com.googlecode.aviator.lexer.ExpressionLexer.scan(ExpressionLexer.java:351)
	at com.googlecode.aviator.parser.ExpressionParser.move(ExpressionParser.java:834)
	at com.googlecode.aviator.parser.ExpressionParser.method(ExpressionParser.java:728)
	at com.googlecode.aviator.parser.ExpressionParser.factor(ExpressionParser.java:590)
	at com.googlecode.aviator.parser.ExpressionParser.unary(ExpressionParser.java:455)
	at com.googlecode.aviator.parser.ExpressionParser.term(ExpressionParser.java:402)
	at com.googlecode.aviator.parser.ExpressionParser.expr(ExpressionParser.java:384)
	at com.googlecode.aviator.parser.ExpressionParser.shift(ExpressionParser.java:347)
	at com.googlecode.aviator.parser.ExpressionParser.rel(ExpressionParser.java:317)
	at com.googlecode.aviator.parser.ExpressionParser.equality(ExpressionParser.java:280)
	at com.googlecode.aviator.parser.ExpressionParser.bitAnd(ExpressionParser.java:241)
	at com.googlecode.aviator.parser.ExpressionParser.xor(ExpressionParser.java:227)
	at com.googlecode.aviator.parser.ExpressionParser.bitOr(ExpressionParser.java:209)
	at com.googlecode.aviator.parser.ExpressionParser.and(ExpressionParser.java:259)
	at com.googlecode.aviator.parser.ExpressionParser.join(ExpressionParser.java:166)
	at com.googlecode.aviator.parser.ExpressionParser.ternary(ExpressionParser.java:145)
	at com.googlecode.aviator.parser.ExpressionParser.statement(ExpressionParser.java:859)
	at com.googlecode.aviator.parser.ExpressionParser.parse(ExpressionParser.java:849)
	at com.googlecode.aviator.AviatorEvaluatorInstance.innerCompile(AviatorEvaluatorInstance.java:678)
	at com.googlecode.aviator.AviatorEvaluatorInstance.compile(AviatorEvaluatorInstance.java:657)
	at com.googlecode.aviator.AviatorEvaluator.compile(AviatorEvaluator.java:400)
	at com.googlecode.aviator.AviatorEvaluator.compile(AviatorEvaluator.java:411)

**Comment by FMX** [comment]
aviator 和 siddhi 引擎对于转义字符的处理模式不通，我自己弄混了。
