### ISSUE TITLE
能否实现带单位的比较

### ISSUE THREAD

**Issue by YuanZhencai** [killme2008/aviator#201]
比如想要实现 `dosage > '10 ml'`，现在的处理方式是 `dosage.unit == 'ml' && dosage.value > 10`

**Comment by killme2008** [comment]
你可以重载运算符去支持 ，特殊处理下参数再比较

https://github.com/killme2008/aviator/wiki#%E9%87%8D%E8%BD%BD%E8%BF%90%E7%AE%97%E7%AC%A6

**Comment by killme2008** [comment]
有更好的方式，假设你的 dosage 的类型是 Price，提供一个自定义函数，接受字符串，转成 price，表达式修改为

`dosage > price('10 ml')`

在 price 函数里处理字符串到 Price 对象的转换，然后实现 Price 对象的 compare 方法即可。

**Comment by YuanZhencai** [comment]
我就想要实现 `UnitNumber > '10 kg'`，如果单位不一样的话都是返回 `false`， 不想用 `function` 实现。

1. 封装了个类 `UnitNumber`
```java
public class UnitNumber implements Comparable<Object> {

  private BigDecimal value;

  private String unit;

  public UnitNumber(BigDecimal value, String unit) {
    this.value = value;
    this.unit = unit;
  }

  public UnitNumber(String numberSpaceUnit) {
    if (!numberSpaceUnit.contains(" ")) {
      throw new RuntimeException("There must be a space");
    }
    String[] split = numberSpaceUnit.split(" ");
    this.value = new BigDecimal(split[0]);
    this.unit = split[1];
  }

  @Override
  public String toString() {
    return String.format("%s %s", this.value, this.unit);
  }

  @Override
  public int compareTo(Object other) {
    if (!(other instanceof UnitNumber)) {
      other = new UnitNumber(String.valueOf(other));
    }
    UnitNumber otherUnitNumber = (UnitNumber) other;
    if (!unit.equals(otherUnitNumber.unit)) {
      throw new UnitMismatchException(unit, otherUnitNumber.unit);
    }
    return value.compareTo(otherUnitNumber.value);
  }

  @Override
  public boolean equals(Object other) {
    if (this == other) {
      return true;
    }
    return toString().equals(String.valueOf(other));
  }

  @Override
  public int hashCode() {
    return Objects.hash(value, unit);
  }

  public BigDecimal getValue() {
    return value;
  }

  public void setValue(BigDecimal value) {
    this.value = value;
  }

  public String getUnit() {
    return unit;
  }

  public void setUnit(String unit) {
    this.unit = unit;
  }
}
```

2. 测试代码

```java
class UnitNumberTest {

  @Test
  void testCompare() {
    String price = "1.3 元";
    UnitNumber number = new UnitNumber(price);
    assertEquals(0, number.compareTo(price));
    assertEquals(0, number.compareTo(new UnitNumber(price)));
    assertTrue(number.compareTo("1.2 元") > 0);
  }

  @Test
  void testMismatch() {
    UnitNumber weight = new UnitNumber("50 kg");
    UnitNumber height = new UnitNumber("170 cm");
    assertThrows(UnitMismatchException.class, () -> {
      weight.compareTo(height);
    });
  }

  @Test
  void testEval() {
    Map<String, Object> env = new HashMap<>();
    env.put("height", new UnitNumber("170 cm"));
    env.put("height1", new UnitNumber("160 cm"));
    assertTrue((boolean) AviatorEvaluator.execute("height > height1", env));
    Boolean check = null;
    try {
      env.put("weight", new UnitNumber("50 kg"));
      check = (boolean) AviatorEvaluator.execute("weight > height", env);
    } catch (ExpressionRuntimeException e) {
      if (e.getCause() instanceof UnitMismatchException) {
        check = false;
      } else {
        throw e;
      }
    }
    assertFalse(check);
    // 会执行错误
    assertTrue((boolean) AviatorEvaluator.execute("height > '160 cm'", env));

  }
}
```

3. 错误

```
com.googlecode.aviator.exception.ExpressionRuntimeException: Could not compare <String, 160 cm> with <JavaType, height, 170 cm, cn.datarx.analysis.pas.UnitNumber>

	at com.googlecode.aviator.runtime.type.AviatorString.compare(AviatorString.java:130)
	at com.googlecode.aviator.runtime.type.AviatorJavaType.compare(AviatorJavaType.java:376)
	at Script_1581648082466_2/1062635358.execute0(Unknown Source)
	at com.googlecode.aviator.ClassExpression.execute(ClassExpression.java:73)
	at com.googlecode.aviator.AviatorEvaluatorInstance.execute(AviatorEvaluatorInstance.java:950)
	at com.googlecode.aviator.AviatorEvaluator.execute(AviatorEvaluator.java:519)
	at com.googlecode.aviator.AviatorEvaluator.execute(AviatorEvaluator.java:531)
	at cn.datarx.analysis.pas.UnitNumberTest.testEval(UnitNumberTest.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:675)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:125)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:132)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:124)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:74)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:104)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:62)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:43)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:35)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:202)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:198)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:69)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:229)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:197)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:191)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)

```

**Comment by YuanZhencai** [comment]
其实跟 `Date` 类型比较一样，不知道能否扩转？

**Comment by AJ-Liang** [comment]
感觉这是边界问题，中间件类型的产品不应该加入过多的业务需求，更应该专注于基础的稳定与可扩展

**Comment by YuanZhencai** [comment]
修改了下 `AviatorString` 的源码，不知道有没有更好的方式
```java
if (otherJavaValue instanceof Date) {
            return this.tryCompareDate((Date)otherJavaValue);
          }

          // 新添加的逻辑
          if (otherJavaValue instanceof Comparable) {
            int compare = ((Comparable) otherJavaValue).compareTo(this.lexeme);
            if (compare > 0)  {
              return  -1;
            } else if(compare < 0)  {
              return  1;
            } else {
              return compare;
            }
          }
          // 新添加的逻辑

          throw new ExpressionRuntimeException("Could not compare " + this.desc(env) + " with " + other.desc(env));
```

**Comment by killme2008** [comment]
前面已经贴了链接了，你要重载预算符
