### ISSUE TITLE
公式编译出错，公式中自定义函数中传字符串是否有长度限制？

### ISSUE THREAD

**Issue by kongkong4556** [killme2008/aviator#230]
Caused by: java.lang.ClassFormatError: Unknown constant tag 80 in class file Script_1587887505363_0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
	at com.googlecode.aviator.parser.AviatorClassLoader.defineClass(AviatorClassLoader.java:32)
	at com.googlecode.aviator.code.asm.ClassDefiner.defineClassByClassLoader(ClassDefiner.java:78)
	at com.googlecode.aviator.code.asm.ClassDefiner.defineClass(ClassDefiner.java:69)
	at com.googlecode.aviator.code.asm.ASMCodeGenerator.getResult(ASMCodeGenerator.java:769)
	... 35 more

这个是编译时候报的错，公式使用是通过自定义了一个函数aSum("a*b+......d"),现在问题是 不放入自定义函数a*b+......d 能编译通过，aSum(a*b+......d)能编译通过，但是aSum("a*b+......d")，内部当做字符串时候无法通过，里面的文本长度比较长，大概7万多个字符，所以不知道是不是自定义函数内部传入字符串这块儿有长度限制还是什么问题导致的？

**Comment by killme2008** [comment]
Java 最大字符串字面量长度是 65535
