### ISSUE TITLE
ALWAYS_PARSE_INTEGRAL_NUMBER_INTO_DECIMAL导致表达式中的数组执行失败

### ISSUE THREAD

**Issue by qyf404** [killme2008/aviator#237]
使用aviator 4.2.10执行如下这个单测无法通过. 单测内容是通过表达式获取ip前三段.
```
      @Test
    public void test_ALWAYS_PARSE_INTEGRAL_NUMBER_INTO_DECIMAL() {
        Map<String, Object> map = new HashMap<>();
        map.put("ip", "127.0.0.1");
        String el = "item = string.split(ip,'[.]',-1); item != nil && count(item) > 2 ? string.join(seq.list(item[0],item[1],item[2]), '.') : 'unknown'";
        AviatorEvaluator.setOption(Options.ALWAYS_PARSE_INTEGRAL_NUMBER_INTO_DECIMAL, true);
        Object result = AviatorEvaluator.execute(el, map);
        System.out.println(result);
        assertThat(result, is("127.0.0"));
    }
```
执行时报异常:

```
com.googlecode.aviator.exception.ExpressionRuntimeException: Execute expression error

	at com.googlecode.aviator.ClassExpression.execute(ClassExpression.java:80)
	at com.googlecode.aviator.AviatorEvaluatorInstance.execute(AviatorEvaluatorInstance.java:769)
	at com.googlecode.aviator.AviatorEvaluator.execute(AviatorEvaluator.java:439)
	at com.googlecode.aviator.AviatorEvaluator.execute(AviatorEvaluator.java:451)
	at com.AviatorTest.test_ALWAYS_PARSE_INTEGRAL_NUMBER_INTO_DECIMAL(AviatorTest.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
Caused by: java.lang.IllegalArgumentException: Illegal index <Decimal, 0>
	at com.googlecode.aviator.runtime.type.AviatorJavaType.getElement(AviatorJavaType.java:493)
	at Script_1588938345752_0/1632492873.execute0(Unknown Source)
	at com.googlecode.aviator.ClassExpression.execute(ClassExpression.java:72)
	... 26 more

```
原因是ALWAYS_PARSE_INTEGRAL_NUMBER_INTO_DECIMAL把表达式中的所有数组转成了BigDecimal. 导致数组获取元素时报错. 

具体代码在这里
```
  @Override
  public AviatorObject getElement(Map<String, Object> env, AviatorObject indexObject) {
    Object thisValue = this.getValue(env);
    if (!thisValue.getClass().isArray() && !(thisValue instanceof List)) {
      throw new ExpressionRuntimeException(
          this.desc(env) + " is not a array or list,could not use [] to get element");
    }
    Object indexValue = indexObject.getValue(env);
    if (!this.isInteger(indexValue)) {
      throw new IllegalArgumentException("Illegal index " + indexObject.desc(env));
    }
    int index = ((Number) indexValue).intValue();
    if (thisValue.getClass().isArray()) {
      return new AviatorRuntimeJavaType(Array.get(thisValue, index));
    } else {
      return new AviatorRuntimeJavaType(((List<?>) thisValue).get(index));
    }
  }
```

是否可以这里做个兼容, 如果是number, 则转成int类型?

**Comment by killme2008** [comment]
ok，确实是个问题

**Comment by killme2008** [comment]
Release 5.0.1 https://github.com/killme2008/aviator/releases/tag/aviator-5.0.1
