### ISSUE TITLE
关于examples/if_return.av的使用方式

### ISSUE THREAD

**Issue by kevenYLi** [killme2008/aviator#275]
**背景**
- 版本5.1.2
- if_return.av的代码
```
## examples/if_return.av

if a < b {
  return "a is less than b.";
}

return a - b;
```

**我的问题**

1.  变量没有声明，所以我想着的是从外部输入参数， 但是发现输入的参数获取不到
- 报错如下：
```
Exception in thread "main" com.googlecode.aviator.exception.ExpressionRuntimeException: Could not sub <JavaType, a, null, null> with <JavaType, b, null, null>
	at com.googlecode.aviator.runtime.type.AviatorObject.sub(AviatorObject.java:172)
	at com.googlecode.aviator.runtime.type.AviatorJavaType.sub(AviatorJavaType.java:479)
	at Script_1596683272663_2/2093631819.execute0(Unknown Source)
	at com.googlecode.aviator.ClassExpression.executeDirectly(ClassExpression.java:65)
	at Lambda_1596683272663_1.call(Unknown Source)
	at Script_1596683272609_0/1452126962.execute0(Unknown Source)
	at com.googlecode.aviator.ClassExpression.executeDirectly(ClassExpression.java:65)
	at com.googlecode.aviator.BaseExpression.execute(BaseExpression.java:131)
	at com.googlecode.aviator.Main.main(Main.java:42)
```
- 单步跟踪了一下，发现创建Env的时候，不是直接解析传入的a和b的值，而是把他们包了一层
key: ARGV
value: 入参的String数组
所以导致在env中查找以a或者b为key的value时查找不到。

2. 修改Main.java中的代码，现在可以获取到变量了，但是变量的类型为String，如果a >= b，则导致语句return  a - b;报类型错误, -- 修改的代码为第42行
```java
// 改动前
 exp.execute(exp.newEnv("ARGV", remainArgs));
//改动后
 exp.execute(exp.newEnv(remainArgs));
```
- 改动的报错：
```
Exception in thread "main" com.googlecode.aviator.exception.ExpressionRuntimeException: Could not sub <JavaType, a, 30, java.lang.String> with <JavaType, b, 20, java.lang.String>
	at com.googlecode.aviator.runtime.type.AviatorObject.sub(AviatorObject.java:172)
	at com.googlecode.aviator.runtime.type.AviatorJavaType.sub(AviatorJavaType.java:479)
	at Script_1596683126286_2/2093631819.execute0(Unknown Source)
	at com.googlecode.aviator.ClassExpression.executeDirectly(ClassExpression.java:65)
	at Lambda_1596683126286_1.call(Unknown Source)
	at Script_1596683126211_0/1452126962.execute0(Unknown Source)
	at com.googlecode.aviator.ClassExpression.executeDirectly(ClassExpression.java:65)
	at com.googlecode.aviator.BaseExpression.execute(BaseExpression.java:131)
	at com.googlecode.aviator.Main.main(Main.java:42)
```
- 重现步骤:
是通过IntelliJ IDEA来运行的，配置项目的运行参数为examples/if_return.av a 30 b 20即可

**Comment by killme2008** [comment]
Examples 下的脚本都是通过 https://github.com/killme2008/aviator/blob/master/src/test/java/com/googlecode/aviator/example/RunScriptExample.java 来运行的，自行传入测试的 env。

这些例子没有考虑用 aviator 命令行运行。

**Comment by kevenYLi** [comment]
通过RunScriptExample.java运行也还是报错，主要原因应该是a,b这两个变量没定义。 错误如下：
```
/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin/java -Dfile.encoding=UTF-8 -classpath /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/ext/cldrdata.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/ext/jaccess.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/ext/nashorn.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/ext/zipfs.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/management-agent.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/lib/dt.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/lib/jconsole.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/lib/sa-jdi.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/lib/tools.jar:/Users/liyi/workspace_java/github/aviator/target/test-classes:/Users/liyi/workspace_java/github/aviator/target/classes:/Users/liyi/.m2/repository/junit/junit/4.3.1/junit-4.3.1.jar:/Users/liyi/.m2/repository/commons-beanutils/commons-beanutils/1.9.3/commons-beanutils-1.9.3.jar:/Users/liyi/.m2/repository/commons-logging/commons-logging/1.2/commons-logging-1.2.jar:/Users/liyi/.m2/repository/commons-collections/commons-collections/3.2.2/commons-collections-3.2.2.jar:/Users/liyi/.m2/repository/org/mockito/mockito-all/1.10.19/mockito-all-1.10.19.jar:/Users/liyi/.m2/repository/org/springframework/spring-context/4.3.16.RELEASE/spring-context-4.3.16.RELEASE.jar:/Users/liyi/.m2/repository/org/springframework/spring-aop/4.3.16.RELEASE/spring-aop-4.3.16.RELEASE.jar:/Users/liyi/.m2/repository/org/springframework/spring-beans/4.3.16.RELEASE/spring-beans-4.3.16.RELEASE.jar:/Users/liyi/.m2/repository/org/springframework/spring-core/4.3.16.RELEASE/spring-core-4.3.16.RELEASE.jar:/Users/liyi/.m2/repository/org/springframework/spring-expression/4.3.16.RELEASE/spring-expression-4.3.16.RELEASE.jar com.googlecode.aviator.example.RunScriptExample
[Aviator INFO] Loading custom aviator function class: 'com.googlecode.aviator.runtime.function.custom.AddFunction'.
[Aviator INFO] Total 1 custom functions loaded.
Exception in thread "main" com.googlecode.aviator.exception.ExpressionRuntimeException: Could not sub <JavaType, a, null, null> with <JavaType, b, null, null>
	at com.googlecode.aviator.runtime.type.AviatorObject.sub(AviatorObject.java:172)
	at com.googlecode.aviator.runtime.type.AviatorJavaType.sub(AviatorJavaType.java:479)
	at Script_1597025069206_2/2065951873.execute0(Unknown Source)
	at com.googlecode.aviator.ClassExpression.executeDirectly(ClassExpression.java:65)
	at Lambda_1597025069206_1.call(Unknown Source)
	at Script_1597025069153_0/284720968.execute0(Unknown Source)
	at com.googlecode.aviator.ClassExpression.executeDirectly(ClassExpression.java:65)
	at com.googlecode.aviator.BaseExpression.execute(BaseExpression.java:131)
	at com.googlecode.aviator.BaseExpression.execute(BaseExpression.java:184)
	at com.googlecode.aviator.example.RunScriptExample.main(RunScriptExample.java:22)

Process finished with exit code 1

```

**Comment by killme2008** [comment]
是的，所以我你要传入自己的 env，修改下 RunScript 代码。
例子是给你参考并用来修改的。

**Comment by kevenYLi** [comment]
明白了，多谢
