### ISSUE TITLE
list里面放map，从list的map里取数据解析表达式报异常

### ISSUE THREAD

**Issue by wangxien** [killme2008/aviator#43]
Map<String, Object> map = new HashMap<String, Object>();
        List<Map<String, Object>> sublist = new ArrayList<Map<String, Object>>();
        HashMap<String,Object> sublistmap=new HashMap<String, Object>();
        sublistmap.put("data", "2");
        sublist.add(sublistmap);
        map.put("sublist", sublist);
        HashMap<String, Object> env = new HashMap<String, Object>();
        env.put("mmap", map);
        System.out.println(AviatorEvaluator.execute("mmap.sublist[0].data", env));

Exception in thread "main" com.googlecode.aviator.exception.ExpressionSyntaxErrorException: Syntax error:illegal expression at 16, current token: [type='Number',lexeme='.',index=15]
	at com.googlecode.aviator.parser.ExpressionParser.reportSyntaxError(ExpressionParser.java:622)

**Comment by killme2008** [comment]
请使用引用变量来 `#mmap.sublist[0].data`

**Comment by wangxien** [comment]
经过测试还是报bug        
        Map<String, Object> map = new HashMap<String, Object>();
        List<Map<String, Object>> sublist = new ArrayList<Map<String, Object>>();
        HashMap<String,Object> sublistmap=new HashMap<String, Object>();
        sublistmap.put("data", "2");
        sublist.add(sublistmap);
        map.put("sublist", sublist);
        HashMap<String, Object> env = new HashMap<String, Object>();
        env.put("mmap", map);
        System.out.println(AviatorEvaluator.execute("#mmap.sublist[0].data", env));
       

Exception in thread "main" com.googlecode.aviator.exception.ExpressionRuntimeException: Could not find variable mmap.sublist[0].data
	at com.googlecode.aviator.runtime.type.AviatorJavaType.getValue(AviatorJavaType.java:255)
	at Script_1514354066782_0/635489240.execute0(Unknown Source)
	at com.googlecode.aviator.ClassExpression.execute(ClassExpression.java:49)
	at com.googlecode.aviator.AviatorEvaluator.execute(AviatorEvaluator.java:593)
	at com.googlecode.aviator.AviatorEvaluator.execute(AviatorEvaluator.java:608)

**Comment by wangxien** [comment]
我用的版本是这个，和版本有关吗？
<dependency>
        <groupId>com.googlecode.aviator</groupId>
        <artifactId>aviator</artifactId>
        <version>3.2.0</version>
    </dependency>

**Comment by killme2008** [comment]
这个是 beanutils 的限制了，你需要将这样的需求包装成 bean 来访问了，参考

https://github.com/killme2008/aviator/blob/master/src/test/java/com/googlecode/aviator/test/function/QuoteVarTest.java

**Comment by killme2008** [comment]
想了下，理论上这种情况我也可以在 aviator 这一层做个解决方案，而不仅仅是委托给 beantuils，issue　先开着，后续我实现下，暂时需要你用bean包装的方式。

**Comment by wangxien** [comment]
你好版主，我用bean包装了后还是不行。具体的解决方案还是辛苦版主了。
public class CollectionExample {
	private static Log log = LogFactory.getLog(CollectionExample.class);
	
	private Map<String, Object> map;
	
	public CollectionExample(Map<String, Object> map){
		this.map=map;
	}
	
	public Map<String, Object> getMap() {
		return map;
	}


	public void setMap(Map<String, Object> map) {
		this.map = map;
	}


	public static void main(String[] args) {
        Map<String, Object> map = new HashMap<String, Object>();
        List<Map<String, Object>> sublist = new ArrayList<Map<String, Object>>();
        HashMap<String,Object> sublistmap=new HashMap<String, Object>();
        sublistmap.put("data", "2");
        sublist.add(sublistmap);
        map.put("sublist", sublist);
        HashMap<String, Object> env = new HashMap<String, Object>();
        CollectionExample example=new CollectionExample(map);
        env.put("mmap", example);
        System.out.println(AviatorEvaluator.execute("#mmap.map.sublist[0]", env));
	}
}

Exception in thread "main" com.googlecode.aviator.exception.ExpressionRuntimeException: Could not find variable mmap.map.sublist[0]
	at com.googlecode.aviator.runtime.type.AviatorJavaType.getValue(AviatorJavaType.java:255)
	at Script_1514357361397_0/868089051.execute0(Unknown Source)
	at com.googlecode.aviator.ClassExpression.execute(ClassExpression.java:49)
	at com.googlecode.aviator.AviatorEvaluator.execute(AviatorEvaluator.java:593)
	at com.googlecode.aviator.AviatorEvaluator.execute(AviatorEvaluator.java:608)

**Comment by killme2008** [comment]
请参考我贴的例子代码吧　

https://github.com/killme2008/aviator/blob/master/src/test/java/com/googlecode/aviator/test/function/QuoteVarTest.java

**Comment by wangxien** [comment]
好的

**Comment by Alingww** [comment]
AviatorEvaluator.execute("#mmap.sublist.[0].data", env) 这样写就可以取值了，这个Map,List嵌套取值比较特殊，因为底层使用的是PropertyUtils.getNestedProperty(），大神应该没有测试过这两个类型的取值，文档中也没有说明，看到我的回复，请及时更新文档，我看很多用户都踩坑了。

**Comment by killme2008** [comment]
请参考上面回答，抱歉，我对 commons-beanutils不了解。
