### ISSUE TITLE
咨询下Execute expression error这种异常的抛出场景

### ISSUE THREAD

**Issue by simonHome** [killme2008/aviator#44]
升级3.2后莫名的出现这个问题，web服务重启也没做任何改动又恢复了，不知道这种异常是在什么场景下会抛出来。

com.googlecode.aviator.exception.ExpressionRuntimeException: Execute expression error
Caused by: java.lang.NoClassDefFoundError: Script_1514466240951_0
	at Script_1514466240951_0/136757698.execute0(Unknown Source) ~[na:na]
	at com.googlecode.aviator.ClassExpression.execute(ClassExpression.java:49) ~[aviator-3.2.0.jar:na]
	... 17 common frames omitted
Caused by: java.lang.ClassNotFoundException: Script_1514466240951_0
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1333) ~[catalina.jar:8.0.44]
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1167) ~[catalina.jar:8.0.44]
	... 19 common frames omitted

**Comment by killme2008** [comment]
是用 cache 模式？

**Comment by simonHome** [comment]
嗯
AviatorEvaluator.compile(iExpressionContext.expression(),true).
                execute(ImmutableMap.of(iExpressionContext.alias(), iExpressionContext.getContext()));
iExpressionContext 是一个封装对象

**Comment by killme2008** [comment]
你运行的 jdk 版本是多少？ 能看下设置的 evaluator 的选项都有哪些，比如运行的优化级别等。后续还有没有出现

**Comment by killme2008** [comment]
应该有更完整的堆栈，看起来部分被忽略了。这个问题没有遇到过，猜测跟 tomcat　的类加载机制是不是有一定关系？我测试了一百万个表达式编译和运行，看起来也没有问题。

**Comment by simonHome** [comment]
一直用着都没问题，突然出现的，重启容器后就消失了。。。jdk是1.8 tomcat容器1.8

**Comment by simonHome** [comment]
Caused by: com.googlecode.aviator.exception.ExpressionRuntimeException: Execute expression error
	at com.googlecode.aviator.ClassExpression.execute(ClassExpression.java:53) ~[aviator-3.2.0.jar:na]
	at com.tujia.tns.hds.biz.core.expression.ExpressionService.execute(ExpressionService.java:50) ~[tns-hds-service-1.0.0.jar:na]
	at com.tujia.tns.hds.biz.core.expression.channel.DistributionCalHouseChannelHandler.calOneExpressChannel(DistributionCalHouseChannelHandler.java:51) ~[tns-hds-service-1.0.0.jar:na]
	... 10 common frames omitted
Caused by: java.lang.NoClassDefFoundError: Script_1514534161138_0
	at Script_1514534161138_0/1919622018.execute0(Unknown Source) ~[na:na]
	at com.googlecode.aviator.ClassExpression.execute(ClassExpression.java:49) ~[aviator-3.2.0.jar:na]
	... 12 common frames omitted 堆栈打出来后就只有这些

**Comment by killme2008** [comment]
还有没有继续重现？

**Comment by simonHome** [comment]
没有复现

**Comment by simonHome** [comment]
很好用

**Comment by killme2008** [comment]
那我暂时先关闭了，猜测还是 tomcat 类加载器相关的问题。

**Comment by xiaduoyu** [comment]
我这边springboot项目也到同样的异常，求大神指点
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: com/googlecode/aviator/ClassExpression
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2022) ~[?:?]
	at com.dianrong.loan.service.InvestMatchLoanService.refreshPriorityByStratsWithFuture(InvestMatchLoanService.java:171) ~[settlement-1.215.0-SNAPSHOT.jar!/:?]
	at com.dianrong.loan.service.InvestMatchLoanService$$FastClassBySpringCGLIB$$ac706273.invoke(<generated>) ~[settlement-1.215.0-SNAPSHOT.jar!/:?]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-5.0.8.RELEASE.jar!/:5.0.8.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:684) ~[spring-aop-5.0.8.RELEASE.jar!/:5.0.8.RELEASE]
	at com.dianrong.loan.service.InvestMatchLoanService$$EnhancerBySpringCGLIB$$9602b295.refreshPriorityByStratsWithFuture(<generated>) ~[settlement-1.215.0-SNAPSHOT.jar!/:?]
	at com.dianrong.settlement.facade.InvestMatchLoanFacade.refreshPriorityStrats(InvestMatchLoanFacade.java:494) ~[settlement-1.215.0-SNAPSHOT.jar!/:?]
	at com.dianrong.settlement.facade.InvestMatchLoanFacade.executeInvest(InvestMatchLoanFacade.java:119) ~[settlement-1.215.0-SNAPSHOT.jar!/:?]
	at com.dianrong.settlement.facade.InvestMatchLoanFacade$$FastClassBySpringCGLIB$$88bee0d2.invoke(<generated>) ~[settlement-1.215.0-SNAPSHOT.jar!/:?]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-5.0.8.RELEASE.jar!/:5.0.8.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:684) ~[spring-aop-5.0.8.RELEASE.jar!/:5.0.8.RELEASE]
	at com.dianrong.settlement.facade.InvestMatchLoanFacade$$EnhancerBySpringCGLIB$$1fa4a112.executeInvest(<generated>) ~[settlement-1.215.0-SNAPSHOT.jar!/:?]
	at com.dianrong.settlement.job.InvestMatchLoanJob.executeJob(InvestMatchLoanJob.java:63) ~[settlement-1.215.0-SNAPSHOT.jar!/:?]
	at com.dianrong.settlement.job.SettlementBaseJob.execute(SettlementBaseJob.java:150) ~[settlement-1.215.0-SNAPSHOT.jar!/:?]
	at com.dianrong.settlement.job.SettlementBaseJob.execute(SettlementBaseJob.java:135) ~[settlement-1.215.0-SNAPSHOT.jar!/:?]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202) ~[quartz-2.3.0.jar!/:?]
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) ~[quartz-2.3.0.jar!/:?]

**Comment by xiaduoyu** [comment]
我这边springboot 项目也遇到同样的问题，大神们帮忙看看，java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: com/googlecode/aviator/ClassExpression
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2022) ~[?:?]
	a

**Comment by killme2008** [comment]
@xiaduoyu 这种都是类加载的问题，或者存在多个版本的  aviator 之类，请自行分析了。

**Comment by Planeswalker23** [comment]
jdk1.8，SpringBoot工程，忽然就出现这种情况，开启了cache，获取列表参数（CAPTURE_FUNCTION_ARGS）。

重启之后就恢复如初，但是怕再次出现这样的情况，大神知道这是什么原因吗？


2020-04-03 13:54:45.448 [http-nio-7272-exec-10] ERROR cn.biosan.utils.exception.GlobalExceptionHandler - Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: Script_1585891937470_0
org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: Script_1585891937470_0
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:978)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.biosan.cloud.BiosanFilter.config.StartFilter.doFilter(StartFilter.java:48)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:123)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:110)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:96)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:167)
        at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:80)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at cn.biosan.serviceblock.security.BiosFilter.doFilter(BiosFilter.java:29)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:106)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
