### ISSUE TITLE
Map取值，带有中划线，会当成减号处理，怎么才能正确取值

### ISSUE THREAD

**Issue by jounghu** [killme2008/aviator#61]
数据如下

```java
     String s = "{\n" +
                "  \"Origin\": \"chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop\",\n" +
                "  \"Accept\": \"*/*\",\n" +
                "  \"User-Agent\": \"Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36\",\n" +
                "  \"Connection\": \"keep-alive\",\n" +
                "  \"Host\": \"localhost:8081\",\n" +
                "  \"Accept-Encoding\": \"gzip, deflate, br\",\n" +
                "  \"Cache-Control\": \"no-cache\",\n" +
                "  \"Remote-Address\": \"0:0:0:0:0:0:0:1\",\n" +
                "  \"Postman-Token\": \"79a9fae1-4615-97ce-8ea3-7d49fa1ca20d\",\n" +
                "  \"Accept-Language\": \"zh,en-US;q=0.9,en;q=0.8\",\n" +
                "  \"Content-Length\": \"16\",\n" +
                "  \"__TypeId__\": \"com.fasterxml.jackson.databind.node.ObjectNode\",\n" +
                "  \"Content-Type\": \"application/json\"\n" +
                "}";
```

取值：
```java
 // 省略str to map
 Object user_agent = AviatorEvaluator.execute("User-Agent",map);
```

异常堆栈：

```java
Exception in thread "main" com.googlecode.aviator.exception.ExpressionRuntimeException: Could not sub JavaType(null, null) with JavaType(null, null)
	at com.googlecode.aviator.runtime.type.AviatorObject.sub(AviatorObject.java:120)
	at com.googlecode.aviator.runtime.type.AviatorJavaType.sub(AviatorJavaType.java:304)
	at Script_1526979963850_0/1811044090.execute0(Unknown Source)
	at com.googlecode.aviator.ClassExpression.execute(ClassExpression.java:53)
	at com.googlecode.aviator.AviatorEvaluator.execute(AviatorEvaluator.java:642)
	at com.googlecode.aviator.AviatorEvaluator.execute(AviatorEvaluator.java:657)

```

**Comment by killme2008** [comment]
这种场景我想不出为什么要用表达式引擎，你直接 map.get 不就完了。

aviator 是处理一些表达式的，不是一个 json parser 啊。

**Comment by killme2008** [comment]
当然，如果你非要这么做的话，可以用 quote var

` AviatorEvaluator.execute("#User-Agent",map);`

在变量前加个井号

**Comment by jounghu** [comment]
@killme2008  上面有很多嵌套 比如我这里是

```json
{
  "headers":{
         
       }
}
```

多层嵌套的场景能使用的！

**Comment by jounghu** [comment]
@killme2008 加上# 还是一样报错

```java
        Object user_agent = AviatorEvaluator.execute("#User-Agent",map);
        System.out.println(user_agent);
```

堆栈

```java
Exception in thread "main" com.googlecode.aviator.exception.ExpressionRuntimeException: Could not sub JavaType(null, null) with JavaType(null, null)
	at com.googlecode.aviator.runtime.type.AviatorObject.sub(AviatorObject.java:120)
	at com.googlecode.aviator.runtime.type.AviatorJavaType.sub(AviatorJavaType.java:304)
	at Script_1526980583127_0/1811044090.execute0(Unknown Source)
	at com.googlecode.aviator.ClassExpression.execute(ClassExpression.java:53)
	at com.googlecode.aviator.AviatorEvaluator.execute(AviatorEvaluator.java:642)
	at com.googlecode.aviator.AviatorEvaluator.execute(AviatorEvaluator.java:657)
```

**Comment by killme2008** [comment]
sorry，我搞错了，这个不支持了，他不是一个xpath类似的东西，抱歉了，或者你可能需要预处理下 map 里的 key，不能有特殊符号，比如加减乘除。

**Comment by jounghu** [comment]
@killme2008  可能我的需求比较奇怪。多谢回答。还有多说一句，就是数字作为key也不能取到。
